name: Publish Docker
on: [push, pull_request, create]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: HurricanKai/Publish-Docker-Github-Action@master
      with:
        name: docker.pkg.github.com/${{ github.repository }}/application
        username: ${{ secrets.GITHUB_DOCKER_USER }}
        password: ${{ secrets.GITHUB_DOCKER_PASSWORD }}
        registry: docker.pkg.github.com
