name: Publish Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: HurricanKai/Publish-Docker-Github-Action@master
      with:
        name: comfortablynumb/golang-testing-template
        username: ${{ secrets.GITHUB_DOCKER_USER }}
        password: ${{ secrets.GITHUB_DOCKER_PASSWORD }}
