name: Publish Docker
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Get the repository name
      id: get_repository_name
      run: echo ::set-output name=REPO_NAME::$(echo "${{ github.repository }}" | cut -d / -f 2)
    - name: Publish to Registry
      uses: jerray/publish-docker-action@master
      with:
        name: docker.pkg.github.com/${{ github.repository }}/${{ steps.get_repository_name.outputs.REPO_NAME }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        repository: ${{ github.repository }}/${{ steps.get_repository_name.outputs.REPO_NAME }}
        registry: docker.pkg.github.com
        auto_tag: true
